seed: 94
device: cuda
output_dir: /volume/med-train/users/dchen02/code/dbMiM/outputs/finetune_cremi_real_unetr_aniso_superhuman_bce_ignore_scratch_r9
pretrained: ''
data:
  synthetic: false
  image_paths:
  - /volume/med-train/users/dchen02/code/dbMiM/data/CREMI
  label_paths:
  - /volume/med-train/users/dchen02/code/dbMiM/data/CREMI
  image_keys:
  - volumes/raw
  - raw
  - main
  label_keys:
  - volumes/labels/neuron_ids
  - labels
  - label
  - gt
  volume_size:
  - 32
  - 160
  - 160
  length_multiplier: 4096
  augment: true
  widen_border: true
  widen_border_radius: 1
model:
  architecture: unetr_aniso
  in_channels: 1
  out_channels: 3
  volume_size:
  - 32
  - 160
  - 160
  patch_size:
  - 4
  - 16
  - 16
  embed_dim: 192
  depth: 6
  num_heads: 6
  feature_size: 32
  dropout: 0.05
train:
  batch_size: 2
  epochs: 200
  max_steps: 30000
  num_workers: 8
  lr: 8.0e-05
  weight_decay: 0.01
  amp: true
  log_every: 20
  eval_every: 0
  eval_max_batches: 0
  save_every: 0
  save_steps: 1000
  val_fraction: 0.0
  clip_grad: 1.0
  replicate_affinity_boundary: true
  loss:
    loss_type: bce
    pos_weight: 1.0
    neg_weight: 1.0
    bce_weight: 1.0
    dice_weight: 0.05
    boundary_dice_weight: 0.35
    channel_weights:
    - 1.25
    - 1.0
    - 1.0
    ignore_label_edges: true
    ignore_label: 0
